image:
  file: .gitpod.Dockerfile

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    visibility: public
    onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - vscjava.vscode-spring-initializr
    - pivotal.vscode-spring-boot
